# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9b0eec3acad45c0c8fe6bb3446d9ec69d6f91eb9971c879f9d04eb5cbe73cb81ad84efdd1837709c13f37a42a6a338c663c75a57f0e6d89763c4f41b138d647

test:
  secret_key_base: 5f8de9f1d29d0d1bd78bc6ebc439c1025eba7c67080f6cfd09640bac37b1f5377b53a122d7a788d3b7838b201ac7c8f559bff04c11a9f514283cb61e748f42e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
